<?php

namespace ESC\MainBundle\Repository;

/**
 * LOLChampionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LOLChampionRepository extends \Doctrine\ORM\EntityRepository
{
}
