<?php

namespace ESC\MainBundle\Repository;

/**
 * LOLSummonerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LOLSummonerRepository extends \Doctrine\ORM\EntityRepository
{
}
